### ISSUE TITLE
Issues with splitter component panedirective children

### ISSUE THREAD

**Issue by Sven65** [syncfusion/ej2-react-ui-components#6]
I have found a couple of issues with the splitter component and its children.

### You can't give the pane directive direct children, for example

```jsx
<SplitterComponent id={'my-splitter'} >
	<PanesDirective>
		<PaneDirective>
			<h1>Hello World!</h1>
		</PaneDirective>
		
		<PaneDirective>
			<h1>Hello World Again!</h1>
		</PaneDirective>
	</PanesDirective>
</SplitterComponent>
```

Does not work.

### You can only pass a function to the `PaneDirective` `content` prop.

```jsx
<PaneDirective
	content={() => <h1>Hello World</h1>}
/>
```
Works, while this does not:

```jsx
<PaneDirective
	content={<h1>Hello World</h1>}
/>
```

### The content does not update.

Take this example;

```jsx
render () {
	const {
		selectedTopic,
	} = this.state

	const topicsList = (
		<TopicsList
			topics={helpMockup}
			onSelectTopic={this.onSelectTopic}
			selectedTopic={selectedTopic}
		/>
	)

	return (
		<SplitterComponent id={'my-splitter'} >
			<PanesDirective>

				{/* Todo */}
				<PaneDirective
					content={() => topicsList}
				/>
				
				<PaneDirective
					content={() => <h1>Viewer</h1>}
				/>
			</PanesDirective>
		</SplitterComponent>
	)
}
```

It should update the props of the `TopicsList` component when the state of my component changes.
It doesn't, and as such, the component itself does not work.

If I instead change my code to not use the SplitterComponent as seen below, it works fine.

```jsx
render () {
	const {
		selectedTopic,
	} = this.state

	return (
		<TopicsList
			topics={helpMockup}
			onSelectTopic={this.onSelectTopic}
			selectedTopic={selectedTopic}
		/>
	)
}
```

**Comment by PrinceOliver** [comment]
Hi @Sven65,

Thank you for sharing detailed information on the issue. 

_**Query 1: You can't give the pane directive direct children. You can only pass a function to the `PaneDirective` `content` prop.**_ 

In the splitter component, you can render direct child of pane directive by using React template function. Kindly refer to the following example for further details: https://stackblitz.com/edit/react-9dmkqn-jxdjrx   

_**Query 2: The content does not update.**_ 

We have validated the reported issue in our end. we are considering this as a defect in our end. The fix for the issue will be included in our patch release scheduled on February 19th, 2019. You can now track the current status of your request, review the proposed resolution timeline, and contact us for any further inquiries through this link: https://www.syncfusion.com/feedback/4736/   

Regards, 
Prince

**Comment by PrinceOliver** [comment]
Hi @Sven65,

Thank you for your patience.

We have fixed the reported issue and the fix is included in the version **16.4.54**. Kindly refer to the following release notes section: https://ej2.syncfusion.com/documentation/release-notes/16.4.54/#splitter 

We suggest you upgrade the packages to the latest version in your end.

Regards,
Prince

**Comment by Sven65** [comment]
Hello, I have checked the latest update, and I can confirm that the issue is still present.

My parent component does update upon state change, but the content I give to the `PaneDirective`s `content` prop as a function does not receive new props, it doesn't even re-render, AT ALL.

**Comment by PrinceOliver** [comment]
Hi @Sven65,

We deeply regret for the inconvenience caused from our end. Due to technical difficulties in our end, the fix is not moved properly in the patch release. This fix will be included in the upcoming **2019, Volume 1 beta release** which is schedule to be rolled out on March 2019. Please track the status through the following feedback link: https://www.syncfusion.com/feedback/4736/

Regards,
Prince

**Comment by PrinceOliver** [comment]
Hi @Sven65 ,

We are sorry for the delay. We couldn't include this fix with 2019 Volume 1 release due to its complexity. We raised its priority and we will resolve this issue in our upcoming 2019 Volume 1 SP1 release which is expected to be rolled out by the end of April 2019.  Please track the status through the following feedback link: https://www.syncfusion.com/feedback/4736/

Regards,
Prince

**Comment by PrinceOliver** [comment]
Hi @Sven65,

Thank you for your patience.

We have fixed the reported issue in our end and it is included in the latest release version **17.1.49**

Sample link: https://stackblitz.com/edit/react-9dmkqn-xetwge 

We suggest you upgrade to the latest version. Let us know if you need any further assistance on this.

Regards,
Prince

**Comment by Sven65** [comment]
As of 17.2.40 this issue is still present, although in a different form this time.

The problem is now that the content of a `TabItemDirective` won't update in a `SplitterComponent`, even with the `delayUpdate` prop being set to true.

**Comment by pandiyarajm93** [comment]
Hi @Sven65 ,

As per our previous updates can render child elements using React template function. The template function invokes at initial load and not updated it content with state content value dynamically.

So setState value change based corresponding state value reflects on child content, we need to do following changes in sample end.

Configure template and data attribute in the content property as follows

`<PaneDirective content=**{{ template: this.leftPane.bind(this), data: { clicks: this.state.clicks } }}** />`

-> **template** - fetch child content from function
-> **data** - Used to pass state value to function as parameters

Also, child content function modified as follows

`
  leftPane(data) { **// Argument used to fetch and update state value**

    return (

      <div>

        <h1>Clicks: {data.clicks}</h1> **// Access function arguments value**

      </div>

    );

  }
`

We have modified your sample with latest packages and above solution, check this below link

https://stackblitz.com/edit/react-9dmkqn-pzcgtb?file=index.js

Also, we have prepared a sample for **SplitterComponent** with **TabComponent** to update state value to content update example. Check this below link

https://stackblitz.com/edit/react-6jhsbj?file=index.js

If you still facing issues, kindly modify the shared sample and revert to us

Regards,
Pandiyaraj M

**Comment by cgsouthey** [comment]
Hi,

I was facing the same issue (content of PaneDirective not updating) - and came across this post. I have now implement the Template to fix this like so...

```
        const { email } = this.props; //Mapped from React-Redux state
....
            <SplitterComponent id="horizontal" width='100%' separatorSize='4'>
                <PanesDirective>
                    <PaneDirective size='30%' content={this.MailBox}/> // LHS
                    <PaneDirective size='70%' content={{ template: this.ReadingPane.bind(this), data: email }}/>// RHS
                </PanesDirective>
            </SplitterComponent>
```

This indeed causes the ReadingPane component to be updated when the value of "email" changes - BUT it also causes the content of the LEFT HAND PaneDirective to re-render - which causes unnecessary flickering and resets its state back to the initial state every time.  How can I get it so ONLY the content that depends on  the "email" component gets re-rendered? I've tried adding a shouldComponentUpdate method to Mailbox to return false but it doesn't work.

Regards,

Charles

**Comment by NarayanasamyP** [comment]
Hi Charles,

Due to state changes causes re-rendering of ejs components, so you may experience splitter get flickering. We have already considered ‘updating value to ejs components through state changes’ as improvement from our end. This improvement with function template rendering will be include in the upcoming Volume-2 main release.

Now you can track status of the improvement task from following feedback link: https://www.syncfusion.com/feedback/12649/

Regards,
Narayanasamy P.

**Comment by rajendranr-5483** [comment]
@cgsouthey ,

We are closing this thread now. We can follow-up on this requirement in corresponding feedback.
